# Generated by Django 2.1.2 on 2018-10-27 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='measure',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Sensor'),
        ),
    ]
